// Offline cache for the installable PWA. GENERATED by tools/build-sw.mjs,
// do not edit by hand: run `node tools/build-sw.mjs` after changing files.
//
// Update strategy: each release is one cache (version + content hash). A new
// service worker installs the complete new set in the background and waits;
// the game offers "update ready" and switches only after saving, so a page
// never runs a mix of old and new modules. The first install takes over at once.
const CACHE = 'tracklands-3.0.0-5aaf933747';
const ASSETS = [
  './',
  './assets/music/README.md',
  './assets/music/music.json',
  './icons/icon-192.png',
  './icons/icon-512.png',
  './icons/icon-maskable-512.png',
  './icons/icon.svg',
  './index.html',
  './manifest.json',
  './src/Game.js',
  './src/audio/Audio.js',
  './src/audio/MusicManager.js',
  './src/config.js',
  './src/core/CameraController.js',
  './src/core/Input.js',
  './src/core/Log.js',
  './src/core/ModelBuilder.js',
  './src/debug/EconomySim.js',
  './src/debug/RailFuzz.js',
  './src/debug/RailTests.js',
  './src/economy/Economy.js',
  './src/economy/Ledger.js',
  './src/economy/Ratings.js',
  './src/i18n.js',
  './src/i18n_rail.js',
  './src/main.js',
  './src/progression/Progression.js',
  './src/progression/Stats.js',
  './src/rail/Construction.js',
  './src/rail/PaxFlow.js',
  './src/rail/RailFurniture.js',
  './src/rail/RailNetwork.js',
  './src/rail/RailRenderer.js',
  './src/rail/StationModels.js',
  './src/rail/Stations.js',
  './src/rail/Works.js',
  './src/road/Crossings.js',
  './src/road/Roads.js',
  './src/save/Save.js',
  './src/services/Monetization.js',
  './src/style.js',
  './src/title/TitleScene.js',
  './src/trains/Consist.js',
  './src/trains/Lines.js',
  './src/trains/Livery.js',
  './src/trains/Maintenance.js',
  './src/trains/TrainModels.js',
  './src/trains/Trains.js',
  './src/ui/AuthorityUI.js',
  './src/ui/DriverUI.js',
  './src/ui/FinanceUI.js',
  './src/ui/Handbook.js',
  './src/ui/IndustryUI.js',
  './src/ui/LiveryEditor.js',
  './src/ui/NetworkMap.js',
  './src/ui/NewsUI.js',
  './src/ui/Overlays.js',
  './src/ui/RailUI.js',
  './src/ui/RoadUI.js',
  './src/ui/ScenarioMenu.js',
  './src/ui/Tutorial.js',
  './src/ui/UI.js',
  './src/ui/icons.js',
  './src/util.js',
  './src/vfx/Particles.js',
  './src/world/Authority.js',
  './src/world/Company.js',
  './src/world/Decor.js',
  './src/world/Environment.js',
  './src/world/Heightmap.js',
  './src/world/Industries.js',
  './src/world/News.js',
  './src/world/Rivals.js',
  './src/world/Scenarios.js',
  './src/world/Towns.js',
  './src/world/WorldGen.js',
  './src/world/WorldView.js',
  './styles/main.css',
  './vendor/three/LICENSE',
  './vendor/three/three.core.js',
  './vendor/three/three.module.js',
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => { if (!self.registration.active) return self.skipWaiting(); }));
});

self.addEventListener('message', (e) => { if (e.data === 'skipWaiting') self.skipWaiting(); });

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('tracklands-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});

// cache first from this release's cache; anything not in it comes from the
// network (and is kept for offline use); offline navigation falls back to the game
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(caches.open(CACHE).then((c) => c.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
    if (res && res.ok) c.put(req, res.clone());
    return res;
  }).catch(() => (req.mode === 'navigate' ? c.match('./index.html') : Response.error())))));
});
