// Everyday words for FIND (Phase 13): what players type, per language, for
// each command FIND offers ("act:arg" as in ToolsUI COMMANDS). Local data
// only: nothing leaves the device and no answer is ever executed by itself —
// FIND lists the command and the player chooses it.
// Aliases are matched after normalisation (lower case, no accents, hyphens
// as spaces, simple plural endings), exactly or as a word prefix, and with a
// small typo allowance (ToolsUI.searchScore).
export const SEARCH_ALIASES = {
  en: {
    'panel:finance': ['money', 'cash', 'budget', 'accounts', 'income', 'expenses', 'profit', 'loan', 'bank', 'balance', 'ledger', 'costs'],
    'tool:bulldoze': ['demolish', 'delete', 'remove', 'destroy', 'destroy building', 'bulldozer', 'tear down', 'clear', 'erase'],
    'tool:roadstop': ['bus stop', 'bus station', 'stop', 'tram stop', 'bus terminal', 'harbour', 'port', 'airport', 'dock'],
    'overlay:traffic': ['traffic', 'busy track', 'track use', 'usage'],
    'overlay:congestion': ['traffic jam', 'jam', 'congestion', 'queue', 'waiting trains', 'bottleneck'],
    'panel:collection': ['vehicle catalogue', 'vehicle catalog', 'vehicle shop', 'rolling stock', 'catalogue', 'catalog', 'vehicles', 'locomotives', 'locos', 'buy train', 'trains shop', 'models'],
    'panel:trains': ['fleet', 'my trains', 'send train to depot', 'train to depot', 'depot orders', 'vehicles list', 'transport overview', 'lines overview'],
    'tool:depot': ['depot', 'train depot', 'engine shed', 'yard', 'garage'],
    'metro:1': ['metro', 'subway', 'underground', 'underground railway', 'tube', 'u bahn', 'tunnel track', 'build metro', 'metro line'],
    'layerview:': ['underground view', 'show underground', 'layers', 'tunnels view', 'see tunnels'],
    'metromap:': ['metro map', 'subway map', 'underground map', 'network map', 'line map'],
    'trackmode:pair': ['four track', 'four tracks', 'quadruple track', 'second pair', 'express tracks', 'express track', 'passing tracks', 'parallel track'],
    'trackmode:role': ['track roles', 'express', 'freight track', 'local track'],
    'panel:plans': ['blueprint', 'blueprints', 'plan', 'plans', 'project', 'projects', 'planning', 'planning mode', 'draft'],
    'planmode:1': ['planning mode', 'plan mode', 'draw plan', 'plan without building'],
    'tool:track': ['rail', 'rails', 'railway', 'track', 'lay track', 'build track'],
    'tool:station': ['station', 'platform', 'build station', 'train station', 'halt'],
    'tool:signal': ['signal', 'signals', 'semaphore', 'block signal', 'path signal'],
    'tool:road': ['road', 'street', 'build road', 'highway'],
    'tool:line': ['bus line', 'route', 'bus route', 'tram line'],
    'tool:industry': ['industry', 'factory', 'mine', 'farm'],
    'panel:research': ['research', 'technology', 'tech tree', 'upgrades', 'unlock'],
    'panel:company': ['company', 'headquarters', 'hq', 'brand', 'logo'],
    'panel:contracts': ['contracts', 'deliveries', 'orders', 'jobs'],
    'panel:objectives': ['objectives', 'goals', 'missions', 'tasks'],
    'panel:map': ['map', 'minimap', 'overview map', 'world map'],
    'panel:news': ['news', 'newspaper', 'events', 'messages'],
    'panel:lists': ['lists', 'list', 'all stations', 'all trains'],
    'panel:settings': ['settings', 'options', 'preferences', 'sound', 'volume', 'graphics', 'language'],
    'panel:handbook': ['help', 'handbook', 'manual', 'how to', 'guide', 'tutorial'],
    'backups:': ['save', 'load', 'backup', 'saves', 'savegame', 'restore'],
    'photo:': ['photo', 'screenshot', 'camera', 'cinematic'],
    'overlay:profit': ['profit map', 'earnings', 'losses'],
    'overlay:towns': ['towns overlay', 'relationship', 'rating'],
    'overlay:industry': ['industry overlay', 'supply'],
  },
  de: {
    'panel:finance': ['geld', 'kasse', 'budget', 'einnahmen', 'finanzen', 'ausgaben', 'gewinn', 'kredit', 'bank', 'konto', 'kontostand', 'kosten', 'bilanz', 'betriebskosten'],
    'tool:bulldoze': ['abreissen', 'abriss', 'abbrechen', 'loeschen', 'löschen', 'entfernen', 'gebaeude entfernen', 'gebäude entfernen', 'zerstoeren', 'zerstören', 'planieren', 'bulldozer'],
    'tool:roadstop': ['bushaltestelle', 'busbahnhof', 'haltestelle', 'strassenbahnhaltestelle', 'straßenbahnhaltestelle', 'hafen', 'flughafen', 'anleger'],
    'overlay:traffic': ['verkehr', 'verkehrsdichte', 'auslastung', 'belegung'],
    'overlay:congestion': ['stau', 'staus', 'warteschlange', 'engpass', 'wartende zuege', 'wartende züge'],
    'panel:collection': ['fahrzeugkatalog', 'fahrzeuge', 'zugkatalog', 'katalog', 'lokomotiven', 'loks', 'zug kaufen', 'rollmaterial', 'modelle'],
    'panel:trains': ['fuhrpark', 'meine zuege', 'meine züge', 'zug ins depot', 'zuege ins depot', 'ins depot', 'depotauftrag', 'verkehrsuebersicht', 'verkehrsübersicht', 'linienuebersicht'],
    'tool:depot': ['depot', 'betriebswerk', 'lokschuppen', 'werkstatt', 'garage'],
    'metro:1': ['u bahn', 'ubahn', 'metro', 'untergrundbahn', 'tunnelstrecke', 'metro bauen', 'u bahn bauen', 'metrolinie'],
    'layerview:': ['untergrundansicht', 'untergrund', 'ebenen', 'tunnel zeigen', 'tunnelansicht'],
    'metromap:': ['u bahn karte', 'metro karte', 'metrokarte', 'netzplan', 'liniennetz', 'netzkarte'],
    'trackmode:pair': ['viergleisig', 'vier gleise', 'zweites gleispaar', 'zweites paar', 'expressgleise', 'fernbahngleise', 'ueberholgleise', 'überholgleise', 'parallelgleis'],
    'trackmode:role': ['gleisrollen', 'expressgleis', 'gueterzuggleis', 'güterzuggleis', 'nahverkehrsgleis'],
    'panel:plans': ['blaupause', 'blaupausen', 'bauplan', 'bauplaene', 'baupläne', 'plan', 'plaene', 'pläne', 'projekt', 'projekte', 'planung', 'planungsmodus', 'entwurf'],
    'planmode:1': ['planungsmodus', 'planmodus', 'plan zeichnen', 'planen ohne bauen'],
    'tool:track': ['gleis', 'gleise', 'schiene', 'schienen', 'strecke', 'gleis bauen', 'bahnstrecke'],
    'tool:station': ['bahnhof', 'bahnsteig', 'bahnhof bauen', 'station', 'haltepunkt'],
    'tool:signal': ['signal', 'signale', 'formsignal', 'blocksignal', 'wegsignal'],
    'tool:road': ['strasse', 'straße', 'strassen', 'straßen', 'strasse bauen', 'straße bauen', 'autobahn'],
    'tool:line': ['buslinie', 'linie', 'route', 'strassenbahnlinie', 'straßenbahnlinie'],
    'tool:industry': ['industrie', 'fabrik', 'mine', 'bauernhof', 'betrieb'],
    'panel:research': ['forschung', 'technologie', 'technik', 'freischalten', 'verbesserungen'],
    'panel:company': ['firma', 'unternehmen', 'zentrale', 'hauptsitz', 'marke', 'logo'],
    'panel:contracts': ['vertraege', 'verträge', 'auftraege', 'aufträge', 'lieferungen'],
    'panel:objectives': ['ziele', 'aufgaben', 'missionen'],
    'panel:map': ['karte', 'uebersichtskarte', 'übersichtskarte', 'weltkarte', 'minikarte'],
    'panel:news': ['nachrichten', 'zeitung', 'neuigkeiten', 'meldungen'],
    'panel:lists': ['listen', 'liste', 'alle bahnhoefe', 'alle bahnhöfe', 'alle zuege', 'alle züge'],
    'panel:settings': ['einstellungen', 'optionen', 'ton', 'lautstaerke', 'lautstärke', 'grafik', 'sprache'],
    'panel:handbook': ['hilfe', 'handbuch', 'anleitung', 'wie geht', 'einfuehrung', 'einführung', 'tutorial'],
    'backups:': ['speichern', 'laden', 'spielstand', 'spielstaende', 'spielstände', 'sicherung', 'wiederherstellen'],
    'photo:': ['foto', 'fotomodus', 'bildschirmfoto', 'kamera', 'kinomodus'],
    'overlay:profit': ['gewinnkarte', 'ertrag', 'verluste'],
    'overlay:towns': ['staedte ansicht', 'städte ansicht', 'beziehung', 'ansehen'],
    'overlay:industry': ['industrie ansicht', 'versorgung'],
  },
};
