#!/usr/bin/env node
// Regenerates service-worker.js: the offline asset list (every file the game
// loads) and a cache name derived from the game version plus a content hash,
// so every release installs as one consistent set and players never run a
// mix of old and new modules.
//
//   node tools/build-sw.mjs          write service-worker.js
//   node tools/build-sw.mjs --check  exit 1 if service-worker.js is stale (tests/CI)
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const DIRS = ['src', 'styles', 'vendor/three', 'icons'];
const FILES = ['index.html', 'manifest.json'];

function walk(dir) {
  const out = [];
  for (const e of fs.readdirSync(path.join(ROOT, dir), { withFileTypes: true })) {
    const rel = path.posix.join(dir, e.name);
    if (e.isDirectory()) out.push(...walk(rel));
    else if (!e.name.startsWith('.')) out.push(rel);
  }
  return out;
}

export function buildServiceWorker() {
  const files = [...FILES, ...DIRS.flatMap(walk)].sort();
  const hash = crypto.createHash('sha256');
  for (const f of files) { hash.update(f); hash.update(fs.readFileSync(path.join(ROOT, f))); }
  const version = (fs.readFileSync(path.join(ROOT, 'src/config.js'), 'utf8').match(/GAME_VERSION = '([^']+)'/) || [])[1] || '0';
  const cache = `tracklands-${version}-${hash.digest('hex').slice(0, 10)}`;
  const assets = ['./', ...files.map((f) => './' + f)];
  return `// Offline cache for the installable PWA. GENERATED by tools/build-sw.mjs,
// do not edit by hand: run \`node tools/build-sw.mjs\` after changing files.
//
// Update strategy: each release is one cache (version + content hash). A new
// service worker installs the complete new set in the background and waits;
// the game offers "update ready" and switches only after saving, so a page
// never runs a mix of old and new modules. The first install takes over at once.
const CACHE = '${cache}';
const ASSETS = [
${assets.map((a) => `  '${a}',`).join('\n')}
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => { if (!self.registration.active) return self.skipWaiting(); }));
});

self.addEventListener('message', (e) => { if (e.data === 'skipWaiting') self.skipWaiting(); });

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('tracklands-') && k !== CACHE).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});

// cache first from this release's cache; anything not in it comes from the
// network (and is kept for offline use); offline navigation falls back to the game
self.addEventListener('fetch', (e) => {
  const req = e.request;
  if (req.method !== 'GET' || new URL(req.url).origin !== self.location.origin) return;
  e.respondWith(caches.open(CACHE).then((c) => c.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
    if (res && res.ok) c.put(req, res.clone());
    return res;
  }).catch(() => (req.mode === 'navigate' ? c.match('./index.html') : Response.error())))));
});
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const out = buildServiceWorker();
  const file = path.join(ROOT, 'service-worker.js');
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (cur !== out) { console.error('service-worker.js is stale: run node tools/build-sw.mjs'); process.exit(1); }
    console.log('service-worker.js is up to date');
  } else {
    fs.writeFileSync(file, out);
    console.log('wrote service-worker.js');
  }
}
