#!/usr/bin/env node
// Regenerates service-worker.js: the offline asset list (every file the game
// loads) and a cache name derived from the game version plus a content hash,
// so every release installs as one consistent set and players never run a
// mix of old and new modules.
//
//   node tools/build-sw.mjs          write service-worker.js
//   node tools/build-sw.mjs --check  exit 1 if service-worker.js is stale (tests/CI)
import fs from 'fs';
import path from 'path';
import crypto from 'crypto';
import { fileURLToPath } from 'url';
import { ROOT, runtimeFiles, gameVersion } from './runtime-files.mjs';

// music tracks are not part of the release download (tens of megabytes): the
// service worker keeps each track once it has been played, in a cache of its
// own that survives game updates as long as the music files do not change
export const MUSIC_FILE = /^assets\/music\/[^/]+\.(ogg|mp3|m4a|opus|wav|webm)$/i;
const MUSIC_URL = String.raw`/assets/music/[^/]+\.(ogg|mp3|m4a|opus|wav|webm)$`;

export function buildServiceWorker() {
  const all = runtimeFiles();
  const files = all.filter((f) => !MUSIC_FILE.test(f));
  const music = all.filter((f) => MUSIC_FILE.test(f));
  const hash = crypto.createHash('sha256');
  for (const f of files) { hash.update(f); hash.update(fs.readFileSync(path.join(ROOT, f))); }
  const mhash = crypto.createHash('sha256');
  for (const f of music) { mhash.update(f); mhash.update(fs.readFileSync(path.join(ROOT, f))); }
  const version = gameVersion();
  const cache = `tracklands-${version}-${hash.digest('hex').slice(0, 10)}`;
  const musicCache = `tracklands-music-${mhash.digest('hex').slice(0, 10)}`;
  const assets = ['./', ...files.map((f) => './' + f)];
  return `// Offline cache for the installable PWA. GENERATED by tools/build-sw.mjs,
// do not edit by hand: run \`node tools/build-sw.mjs\` after changing files.
//
// Update strategy: each release is one cache (version + content hash). A new
// service worker installs the complete new set in the background and waits;
// the game offers "update ready" and switches only after saving, so a page
// never runs a mix of old and new modules. The first install takes over at once.
// Music tracks (${music.length}) are cached when first played, in MUSIC.
const CACHE = '${cache}';
const MUSIC = '${musicCache}';
const MUSIC_FILE = new RegExp(${JSON.stringify(MUSIC_URL)}, 'i');
const ASSETS = [
${assets.map((a) => `  '${a}',`).join('\n')}
];

self.addEventListener('install', (e) => {
  e.waitUntil(caches.open(CACHE).then((c) => c.addAll(ASSETS)).then(() => { if (!self.registration.active) return self.skipWaiting(); }));
});

self.addEventListener('message', (e) => { if (e.data === 'skipWaiting') self.skipWaiting(); });

self.addEventListener('activate', (e) => {
  e.waitUntil(caches.keys().then((keys) => Promise.all(keys.filter((k) => k.startsWith('tracklands-') && k !== CACHE && k !== MUSIC).map((k) => caches.delete(k)))).then(() => self.clients.claim()));
});

// cache first from this release's cache; anything not in it comes from the
// network (and is kept for offline use); offline navigation falls back to the game
self.addEventListener('fetch', (e) => {
  const req = e.request;
  const url = new URL(req.url);
  if (req.method !== 'GET' || url.origin !== self.location.origin) return;
  // music: from its own cache, else the network (then kept for next time)
  if (MUSIC_FILE.test(url.pathname)) {
    e.respondWith(caches.open(MUSIC).then((c) => c.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
      if (res && res.status === 200) c.put(req, res.clone());
      return res;
    }))));
    return;
  }
  e.respondWith(caches.open(CACHE).then((c) => c.match(req, { ignoreSearch: true }).then((hit) => hit || fetch(req).then((res) => {
    if (res && res.ok) c.put(req, res.clone());
    return res;
  }).catch(() => (req.mode === 'navigate' ? c.match('./index.html') : Response.error())))));
});
`;
}

if (process.argv[1] && fileURLToPath(import.meta.url) === path.resolve(process.argv[1])) {
  const out = buildServiceWorker();
  const file = path.join(ROOT, 'service-worker.js');
  if (process.argv.includes('--check')) {
    const cur = fs.existsSync(file) ? fs.readFileSync(file, 'utf8') : '';
    if (cur !== out) { console.error('service-worker.js is stale: run node tools/build-sw.mjs'); process.exit(1); }
    console.log('service-worker.js is up to date');
  } else {
    fs.writeFileSync(file, out);
    console.log('wrote service-worker.js');
  }
}
