// What changed, newest first (the Changelog panel: Settings → What's new).
// Each entry: version, month, and short lines in English and German.
export const CHANGELOG = [
  {
    v: '6.2.0', date: '2026-10',
    en: [
      'TRACKLANDS is also an app now: a Windows installer and an Android app with the same game, running fully offline',
      'Android: Back closes what is open first (dialog, panel, tool, underground view); on an empty screen press it twice to leave',
      'In the apps, save exports, diagnostics and photos are saved through the system’s Save as dialog',
      'Credits show the exact build and platform',
      'A train that lost its way is put back on its own company’s line, never on a rival’s platform or a platform no track reaches',
    ],
    de: [
      'TRACKLANDS gibt es jetzt auch als App: ein Installer für Windows und eine Android-App mit demselben Spiel, ganz ohne Internet',
      'Android: Zurück schließt zuerst, was offen ist (Dialog, Panel, Werkzeug, Untergrundansicht); auf leerem Bildschirm zweimal drücken zum Verlassen',
      'In den Apps werden Spielstand-Exporte, Diagnose und Fotos über den „Speichern unter“-Dialog des Systems gesichert',
      'Die Mitwirkenden-Seite zeigt den genauen Build und die Plattform',
      'Ein Zug, der sich verirrt hat, wird auf die Strecke seiner eigenen Firma zurückgesetzt – nie an einen fremden Bahnsteig oder an einen ohne Gleisanschluss',
    ],
  },
  {
    v: '6.1.1', date: '2026-10',
    en: [
      'Start Journey begins a standard world with the tutorial at once; New game… holds every choice, with the expert settings folded away',
      'The game-mode presets in New game, the FIND examples and unchosen filters are readable again; locked research shows what it needs clearly',
      'On a phone the tool strip starts at Select instead of fading it out',
      'Names from imported saves, blueprints, scenarios and content packs can no longer carry markup',
    ],
    de: [
      'Reise beginnen startet sofort eine Standardwelt mit Einführung; Neues Spiel… enthält alle Wahlmöglichkeiten, die Experteneinstellungen eingeklappt',
      'Die Spielmodi unter Neues Spiel, die Beispiele in SUCHEN und nicht gewählte Filter sind wieder lesbar; gesperrte Forschung zeigt klar, was sie braucht',
      'Auf dem Handy beginnt die Werkzeugleiste bei Auswahl, statt sie auszublenden',
      'Namen aus importierten Spielständen, Blaupausen, Szenarien und Inhaltspaketen können kein Markup mehr enthalten',
    ],
  },
  {
    v: '6.1.0', date: '2026-10',
    en: [
      'FIND understands everyday English and German words, typos and accents: "money", "abreißen", "U-Bahn-Karte", "bahnof" — it suggests, you choose',
      'The vehicle catalogue reads a description: "fast electric freight loco from the 60s" fills the filters, shown as chips you can clear',
      'Lifts and escalators at stations where levels meet: quicker changes between metro, viaduct and street',
      'Rival railways renovate only their important stations, rarely, and now and then keep an old one as a listed building',
      'Snow on airport grass, lit terminal windows at night, no hard cloud shadows under the moon',
      'Overlays and signals no longer rely on colour alone: patterns, a legend in words, and stop and clear lamps at different heights',
      'Escape closes one thing at a time, also from a text field; errors say what to do next; the advisor explains its numbers',
      'Faster towns: road traffic takes about a third less time per frame, with the same behaviour',
    ],
    de: [
      'SUCHEN versteht Alltagswörter auf Deutsch und Englisch, Tippfehler und Umlaute: „Geld“, „demolish“, „U-Bahn-Karte“, „bahnof“ — es schlägt vor, du wählst',
      'Der Fahrzeugkatalog liest eine Beschreibung: „schnelle elektrische Güterlok aus den 60ern“ füllt die Filter, als Chips, die du löschen kannst',
      'Aufzüge und Rolltreppen an Bahnhöfen, wo Ebenen zusammentreffen: schnelleres Umsteigen zwischen U-Bahn, Viadukt und Straße',
      'Konkurrenzbahnen renovieren nur ihre wichtigen Bahnhöfe, selten, und behalten ab und zu einen alten als Baudenkmal',
      'Schnee auf dem Flugfeld, beleuchtete Terminalfenster bei Nacht, keine harten Wolkenschatten im Mondlicht',
      'Overlays und Signale nicht mehr nur über Farbe: Muster, eine Legende in Worten und Halt- und Fahrtlampen auf verschiedener Höhe',
      'Escape schließt eins nach dem anderen, auch aus einem Textfeld; Fehler sagen, was zu tun ist; der Berater erklärt seine Zahlen',
      'Schnellere Städte: Der Straßenverkehr braucht etwa ein Drittel weniger Zeit pro Bild, bei gleichem Verhalten',
    ],
  },
  {
    v: '6.0.0', date: '2026-09',
    en: [
      'Metro: underground and elevated railways on their own levels, with portals, street entrances, five metro sets, an underground view and a metro map',
      'Four-track corridors: a second pair with crossovers in one step, local, express and freight roles, and flyovers',
      'Planning mode: draw whole projects without building, see the price, then build all of it or the valid part; blueprints you can rotate, mirror and share',
      'Station complexes with walking interchanges between levels, bike parking and park & ride',
      'Infrastructure looks its age: airports, ports, level crossings, catenary, tunnel portals, metro stations and bus stops keep the look of the year they were built until you renovate them',
      'One construction price: what a plan or preview shows is what is charged',
      'New sounds: metro door chimes, tunnel rumble, harbour and airport ambience, renovation and project fanfares',
      'World information: the year, today\'s building style, terrain and climate',
    ],
    de: [
      'Metro: Untergrund- und Hochbahnen auf eigenen Ebenen, mit Portalen, Straßenzugängen, fünf Metro-Zügen, Untergrundansicht und Metro-Plan',
      'Viergleisige Strecken: ein zweites Gleispaar mit Weichenverbindungen in einem Schritt, Rollen für Nah-, Fern- und Güterverkehr sowie Überwerfungen',
      'Planungsmodus: ganze Projekte zeichnen ohne zu bauen, den Preis sehen, dann alles oder den gültigen Teil bauen; Baupläne drehen, spiegeln und teilen',
      'Bahnhofskomplexe mit Fußwegen zwischen den Ebenen, Fahrradstellplätzen und Park & Ride',
      'Infrastruktur zeigt ihr Alter: Flughäfen, Häfen, Bahnübergänge, Oberleitung, Tunnelportale, Metrostationen und Haltestellen behalten das Aussehen ihres Baujahrs, bis du sie renovierst',
      'Ein Baupreis: Was Plan oder Vorschau zeigen, wird auch berechnet',
      'Neue Klänge: Türsignale der Metro, Tunnelrauschen, Hafen- und Flughafenkulisse, Renovierungs- und Projektfanfaren',
      'Welt-Info: Jahr, heutiger Baustil, Gelände und Klima',
    ],
  },
  {
    v: '5.0.0', date: '2026-09',
    en: [
      'Competitor railways: companies with their own personalities plan, build, run, expand and modernize railways with their own money, and never touch yours',
      'A page for every competitor, a companies overlay, and a flag and livery for their stations and trains',
      'New games: up to eight competitors, when they start and how well they plan',
      'Thirteen terrains, from gentle countryside to alpine, archipelago and a whole continent, with advanced settings and a preview of towns and building costs',
      'Eras you can see: towns grow in layers from an old centre, stations age and can be renovated or listed, semaphores give way to colour lights',
      'Town histories and company milestones, era filters in the catalogue, and six new trains where the eras had gaps',
    ],
    de: [
      'Konkurrierende Eisenbahnen: Firmen mit eigenem Charakter planen, bauen, betreiben, erweitern und modernisieren Strecken mit eigenem Geld und rühren deine nie an',
      'Eine Seite für jede Konkurrenzfirma, eine Firmen-Karte und Flagge und Lackierung für ihre Bahnhöfe und Züge',
      'Neue Spiele: bis zu acht Konkurrenten, wann sie starten und wie gut sie planen',
      'Dreizehn Gelände, von sanftem Hügelland bis Alpen, Inselwelt und einem ganzen Kontinent, mit erweiterten Einstellungen und Vorschau auf Städte und Baukosten',
      'Sichtbare Epochen: Städte wachsen in Schichten um einen alten Kern, Bahnhöfe altern und lassen sich renovieren oder unter Denkmalschutz stellen, Formsignale weichen Lichtsignalen',
      'Stadtgeschichten und Firmen-Meilensteine, Epochenfilter im Katalog und sechs neue Züge, wo den Epochen welche fehlten',
    ],
  },
  {
    v: '4.0.0', date: '2026-09',
    en: [
      'Journeys: passengers and freight travel end to end with a purpose, change vehicles and modes, and pay once on arrival',
      'Service quality, even spacing, express and local stops; city accessibility, land value, districts, commuter belts, tourism and town events',
      'Road types from dirt track to highway, one-way streets, busways, road bridges, tunnels and overpasses',
      'Ports and airports in three sizes with berths and runway slots; new ships and aircraft',
      'Refurbishment and heritage services; reputation, deadline contracts, service levels and town concessions',
      'Finance analysis tab and profit overlay; rival strategies (coaches, town buses, truck freight) and takeovers',
      'Speeds up to 8×, day length, extreme weather, eras; FIND (F), bookmarks and sandbox tools',
      'Save safety: rolling backups, a save health check, crash snapshots and autosave settings',
      'Manufacturers and generations in the vehicle catalogue, with a maker filter',
      'Performance overlay (F3), quicker long lists, and a fix for memory kept between games',
      'Photo mode (P) with a cinematic camera, nine new achievements and more statistics',
    ],
    de: [
      'Reisen: Fahrgäste und Fracht reisen durchgehend mit Zweck, steigen um und zahlen einmal bei Ankunft',
      'Servicequalität, gleichmäßiger Takt, Express- und Nahverkehrshalte; Erreichbarkeit, Bodenwert, Viertel, Pendlergürtel, Tourismus und Stadtereignisse',
      'Straßentypen vom Feldweg bis zur Autobahn, Einbahnstraßen, Bustrassen, Straßenbrücken, Tunnel und Überführungen',
      'Häfen und Flughäfen in drei Größen mit Liegeplätzen und Pistenslots; neue Schiffe und Flugzeuge',
      'Aufarbeitung und Museumsfahrten; Ruf, Verträge mit Fristen, Servicelevel und Stadtkonzessionen',
      'Finanzanalyse und Gewinn-Karte; Konkurrenzstrategien (Fernbusse, Stadtbusse, Lkw-Fracht) und Übernahmen',
      'Bis 8× Geschwindigkeit, Tageslänge, Extremwetter, Epochen; SUCHEN (F), Lesezeichen und Sandbox',
      'Speichersicherheit: rollierende Backups, Spielstand-Check, Absturz-Sicherung und Autosave-Einstellungen',
      'Hersteller und Generationen im Fahrzeugkatalog, mit Herstellerfilter',
      'Leistungsanzeige (F3), schnellere lange Listen und ein Fix für Speicher, der zwischen Spielen liegen blieb',
      'Fotomodus (P) mit Kamerafahrt, neun neue Erfolge und mehr Statistik',
    ],
  },
  {
    v: '3.0.0', date: '2026-09',
    en: [
      'Bus networks with lines, stop types, garages and automatic allocation; road traffic with junctions and lights',
      'Ten city archetypes, new industries and cargo chains, 35 locomotives and units, a vehicle catalogue',
      'Touch construction with handles and Build/Cancel; ambience audio; performance levels of detail',
    ],
    de: [
      'Busnetze mit Linien, Haltestellentypen, Garagen und automatischer Zuteilung; Straßenverkehr mit Kreuzungen und Ampeln',
      'Zehn Stadttypen, neue Industrien und Produktionsketten, 35 Loks und Triebzüge, ein Fahrzeugkatalog',
      'Bauen per Touch mit Anfassern und Bauen/Abbrechen; Umgebungsgeräusche; Detailstufen für Leistung',
    ],
  },
  {
    v: '2.0.0', date: '2026-09',
    en: ['Consists, signalling with blocks and paths, multi-track stations, schedules and overlays'],
    de: ['Zugverbände, Signale mit Blöcken und Fahrstraßen, mehrgleisige Bahnhöfe, Fahrpläne und Overlays'],
  },
];
